### ISSUE TITLE
Missing "xela_dataloader"

### ISSUE THREAD

**Issue by gloriatao** [swchui/Grasping-state-assessment#1]
Hi swchui!

Congrats on the nice job! 

We find that several files are missing. Can you re-upload them?

In line 9, tran.py

**from xela_dataloader import MyDataset**

In line 30, 38, tran.py

xeladataset_train2.csv
xeladataset_test2.csv

Thank you!

**Comment by cui-shaowei** [comment]
The missing files can be found at [https://drive.google.com/drive/folders/1ialG2_z73bw0xYB7KpoNe-kmfED-G1p3?usp=sharing](url).

Thanks for your attention!

**Comment by sthoduka** [comment]
Hello, unfortunately the google drive link does not have the two CSV files (xeladataset_train2.csv, xeladataset_test2.csv). Would it be possible to upload those as well?
Thanks!

**Comment by sthoduka** [comment]
Oh I see now that the train and test dataset have been defined in [xela_dataloader.py](https://github.com/swchui/Grasping-state-assessment/blob/master/xela_dataloader.py#L105) instead of reading from CSV files. Are the label files `test_label_5.npy` and `'train_label_5.npy` still valid for this test/train split?
